---
# tasks file for php
- name: Install openjdk 11 & 8
  become: true
  apt: name={{ item }} state=present
  with_items:
    - openjdk-11-jdk
    - openjdk-8-jdk

- name: Install gradle and groovy
  become: true
  apt: name={{ item }} state=present
  with_items:
    - gradle
    - groovy